#management:
#  security:
#    #是否启用安全
#    enabled: true
#    user:
#        name: demo
#        password: actuator
#endpoints:
#  shutdown:
#    #开启shutdown端点
#    enabled: true
management:
    endpoints:
        web:
        exposure:
            include: health,info,env,metrics,h

########### Zookeeper Configuration Start ###########
zookeeper:
  serverLists: 127.0.0.1:2181 #,127.0.0.1:2182,127.0.0.1:2183
  namespace: cronner
  baseSleepTimeMilliseconds: 1000
  maxSleepTimeMilliseconds: 3000
  maxRetries: 3

    ############ Zookeeper Configuration End ###########

    ########### cronner packege Configuration Start ###########

cronner:
  package: com.springboot2.carrot.timer

    ############ cronner packege Configuration End ###########